name: Build and Test llama.cpp on macOS

on:
  push:
    branches:
      - macos-13
  pull_request:
    branches:
      - macos-13
  workflow_dispatch:  # Manual trigger


jobs:
  build-and-test:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone llama.cpp repository
        run: |
          git clone https://github.com/ggml-org/llama.cpp.git $GITHUB_WORKSPACE/llama.cpp
          cd $GITHUB_WORKSPACE/llama.cpp
          git submodule update --init --recursive

      - name: Set up environment
        run: |
          brew update
          brew install cmake gcc wget libomp

      - name: Download model file
        run: |
          mkdir -p $GITHUB_WORKSPACE/llama.cpp/models/deepseek-r1-distill
          cd $GITHUB_WORKSPACE/llama.cpp/models/deepseek-r1-distill
          wget -O DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M.gguf "https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-1.5B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M.gguf"

          # Verify model download
          echo "Checking if model file exists..."
          ls -lah $GITHUB_WORKSPACE/llama.cpp/models/deepseek-r1-distill

      - name: Build llama.cpp
        run: |
          cd $GITHUB_WORKSPACE/llama.cpp
          mkdir -p build && cd build
          cmake ..
          cmake --build . --parallel $(sysctl -n hw.ncpu)
          ls -lah bin  # Ensure binaries exist

      - name: Verify if llama-run is built
        run: |
          if [ -f "$GITHUB_WORKSPACE/llama.cpp/build/bin/llama-run" ]; then
            echo "llama-run is built successfully."
          else
            echo "llama-run not found. Build might have failed."
            exit 1
          fi

      - name: Debug directory structure
        run: |
          echo "### Listing root directory"
          ls -lah
          echo "### Listing llama.cpp directory"
          ls -lah $GITHUB_WORKSPACE/llama.cpp
          echo "### Listing models directory"
          ls -lah $GITHUB_WORKSPACE/llama.cpp/models
          echo "### Listing deepseek-r1-distill directory"
          ls -lah $GITHUB_WORKSPACE/llama.cpp/models/deepseek-r1-distill
          echo "### Listing build directory"
          ls -lah $GITHUB_WORKSPACE/llama.cpp/build
          echo "### Listing bin directory"
          ls -lah $GITHUB_WORKSPACE/llama.cpp/build/bin

      - name: Run llama with test prompt
        run: |
          cd $GITHUB_WORKSPACE/llama.cpp/build
          MODEL_PATH="$GITHUB_WORKSPACE/llama.cpp/models/deepseek-r1-distill/DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M.gguf"

          if [ -f "./bin/llama-run" ] && [ -f "$MODEL_PATH" ]; then
            echo "Running llama-run..."
            ./bin/llama-run file://$MODEL_PATH "What is DeepSeek R1?"
          else
            echo "ERROR: Either llama-run or the model file is missing!"
            exit 1
          fi
