name: Llama.cpp Test on macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Cache Homebrew Packages
      id: cache
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/Homebrew
          /usr/local/Cellar
          /usr/local/Caskroom
          /usr/local/var/homebrew/linked
        key: ${{ runner.os }}-brew-${{ steps.set-up-homebrew.outputs.cache-key }}
        restore-keys: ${{ runner.os }}-brew-

    - name: Install Dependencies
      run: |
        brew install cmake gcc wget libomp

    - name: Build llama.cpp
      run: |
        mkdir -p build
        cd build
        cmake ..
        cmake --build . --parallel $(sysctl -n hw.ncpu)

    - name: Download Model
      run: |
        mkdir -p models/deepseek-r1-distill/
        wget "https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-1.5B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M.gguf" \
        -O models/deepseek-r1-distill/DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M.gguf

    - name: Run Inference
      run: |
        ./build/bin/main -m models/deepseek-r1-distill/DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M.gguf -p "What is DeepSeek R1?"
